//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreadmore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DMDB : DbContext
    {
        public DMDB()
            : base("name=DMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<core_User> core_User { get; set; }
        public virtual DbSet<movie_Details> movie_Details { get; set; }
        public virtual DbSet<movie_News> movie_News { get; set; }
        public virtual DbSet<movie_Review> movie_Review { get; set; }
        public virtual DbSet<quote_Quote> quote_Quote { get; set; }
        public virtual DbSet<writing_Writing> writing_Writing { get; set; }
    
        public virtual ObjectResult<up_movie_GetReviewerInfo_Result> up_movie_GetReviewerInfo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_movie_GetReviewerInfo_Result>("up_movie_GetReviewerInfo", idParameter);
        }
    }
}
