//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreadmore
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_News
    {
        public int id_MovieNews { get; set; }
        public string IMDB_ID { get; set; }
        public string MovieTitle { get; set; }
        public string News { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<int> NewsBy { get; set; }
    }
}
