//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreadmore
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_Quote
    {
        public int id_Quote { get; set; }
        public string Quote { get; set; }
        public string QuoteBy { get; set; }
        public string QuoteByImage { get; set; }
    }
}
