//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dreadmore
{
    using System;
    using System.Collections.Generic;
    
    public partial class writing_Writing
    {
        public int id_Writing { get; set; }
        public int WritingType { get; set; }
        public string Title { get; set; }
        public int Author { get; set; }
        public string WritingUrl { get; set; }
    }
}
